### ISSUE TITLE
pre-commit integration

### ISSUE THREAD

**Issue by jrottenberg** [Madoshakalaka/pipenv-setup#109]
Hello !

Would you be interested adding a [pre-commit](https://pre-commit.com/) hook to help users running pipenv-setup ?

**Comment by benhowes** [comment]
FWIW, I've been using the following:

```
- repo: local
  hooks:
  - id: pipenv-setup
    name: pipenv-setup
    stages: [commit]
    language: system
    entry: pipenv run pipenv-setup sync
    pass_filenames: false
    files: Pipfile(\.lock)?
```
