### ISSUE TITLE
How to get the pre-commit example working?

### ISSUE THREAD

**Issue by RidaAyed** [Madoshakalaka/pipenv-setup#162]
The [documentation](https://github.com/Madoshakalaka/pipenv-setup/blob/109056e7b33b2ae4242eb56326c4f9bc66dde841/README.md?plain=1#L203) shows `v4.0.0a1` which returns:

`error: pathspec 'v4.0.0a1' did not match any file(s) known to git`

Using `3.2.0` returns `ModuleNotFoundError: No module named 'vistir.compat'`

.pre-commit-config.yaml:
```yaml
repos:
- repo: https://github.com/Madoshakalaka/pipenv-setup
  rev: "v3.2.0" # pick a git hash / tag to point to
  hooks:
    - id: pipenv-setup
      language: python
      entry: pipenv-setup
      language_version: python3
      files: Pipfile(\.lock)?|setup\.py
```
As recommended in #109 my Pipfile does **not** contain `pipenv-setup` but relies on pre-commit's auto-install
However I'm able to run pipenv-setup without pre-commit by installing it **manually** via pipenv and vistir = "0.6.1"
