### ISSUE TITLE
Deprecate support for EOL Python versions on MacOS

### ISSUE THREAD

**Issue by bryant-finney** [Madoshakalaka/pipenv-setup#80]
# Summary 

PR #79 introduces GitHub actions for performing CI/CD. The pipeline executes the test suite across all supported Python versions on multiple operating systems.

actions/virtual-environments#4060 updates the `macOS-latest` workflow to reference `macOS-11` (from `macOS-10.5`); this is expected to remove support for Python versions `2.7`, `3.5`, and `3.6`. Accordingly, the GitHub actions configuration must be updated to accommodate this change.

## Definition of Done 

- CI tests for `macOS` are skipped/allowed to fail/expected to fail for Python `2.7`, `3.5`, and `3.6` on macOS

**Comment by jshwi** [comment]
@bryant-finney 
I've had a look at this. if/else in yaml is pretty clunky (for specifying OS), maybe these versions could be dropped for all OSs as `2.7` and `3.5` are no longer supported by `Pip`? Is `MacOS` prematurely dropping support for `3.6`?

**Comment by jshwi** [comment]
Not sure, I might have a look. That looks like the cleanest and most logical solution. Better than what I was thinking, which was something like:
```yaml
if: matrix.os == 'macOS-latest'
python-version: [3.7, 3.8]
if: matrix.os != 'macOS-latest'
python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
```
